name: Java CI with Maven
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
  compile:
    runs-on: ubuntu-latest
    needs: cancel
    name: Running Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile code
      run: mvn compile
  test:
    runs-on: ubuntu-latest
    name: Running tests
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run unit tests
        run: mvn test
  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate the package
        run: mvn -B package -Dmaven.test.skip=true
      - name: Deploy the package to the remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: target/code-0.0.1-SNAPSHOT.jar
          remote: /home/ubuntu/code-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Start Dispatcher Service
        uses: garygrossgarten/github-action-ssh@release
        with: 
          command: |
            fuser -k 8080/tcp
            java -jar code-0.0.1-SNAPSHOT.jar
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
